# Generated by Django 4.1.5 on 2023-01-08 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Market', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'verbose_name': 'Корзину', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterModelOptions(
            name='basket_product',
            options={'verbose_name': 'Корзину продуктов', 'verbose_name_plural': 'Корзина продуктов'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='product_info',
            options={'verbose_name': 'Информацию о продукте', 'verbose_name_plural': 'Информация о продуктах'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Рейтинг', 'verbose_name_plural': 'Рейтинги'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='rate',
        ),
        migrations.AlterField(
            model_name='basket',
            name='basket_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Market.basket_product', verbose_name='Наименование продукта'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='basket_product',
            name='basket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Market.basket', verbose_name='Корзина пользователя'),
        ),
        migrations.AlterField(
            model_name='basket_product',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Market.product', verbose_name='Наименование продукта'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Наименование категории'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Market.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Наименование продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product_info',
            name='description',
            field=models.CharField(max_length=128, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product_info',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Market.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='product_info',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Market.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rate',
            field=models.PositiveIntegerField(verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
